version: 2.1

parameters:
  hello1:
    type: enum
    default: ["first hello1", "second hello1"]
  hello2:
    type: enum
    default: ["first hello2", "second hello2", "third hello2"]

jobs:
  hello:
    parameters:
      hello1:
        type: string
      hello2:
        type: string
    docker:
      - image: cimg/base:2022.11
    steps:
      - run: echo << parameters.hello1 >>
      - run: echo << parameters.hello2 >>

workflows:
  build-and-test:
    jobs:
      - hello:
          matrix:
            parameters:
              hello1: << pipeline.parameters.matrix1 >>
              hello2: << pipeline.parameters.matrix2 >>
