
version: 2.1

orbs:
  win: circleci/windows@5.0
  maven: circleci/maven@1.4.1

executors:
  maven-win:
    machine:
      image: windows-server-2022-gui:current
      resource_class: windows.medium
      shell: bash.exe

jobs:
  build:
    executor:
      name: win/default
      size: medium
      shell: powershell.exe
    steps:
      - run:
          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          shell: powershell.exe
      - run:
          command: echo hello && echo world
          shell: bash.exe
      - run:
          command: echo hello & echo world
          shell: cmd.exe
      - run:
          command: choco install -y maven --version=3.9.4
          shell: powershell.exe
      - run:
          command: $MVN_PATH/mvn -v
          shell: bash.exe
          when: always

workflows:
  build-workflow:
    jobs:
      - build
      - maven/test:
          executor: maven-win
